services:
  homepage:
    # Build from your local folder instead of using the image
    build:
      context: /home/justin/server/homepage/homepage-src
      dockerfile: Dockerfile # only if your source has a custom Dockerfile
    container_name: homepage
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=0.0.0.0:3000,localhost:3000,192.168.12.126:3000
      - PUID=1000
      - PGID=1000
    ports:
      - "3000:3000"
    volumes:
      - /home/justin/server/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

